<?php

namespace BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{

    public function findByUser($id){

        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
            ->where('u.utilisateur = :id' )
            ->orderBy('u.date')
            ->setParameter('id' ,$id);

        return $qb->getQuery()->getResult();

    }
}
