<?php

namespace BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends EntityRepository
{

    public function byPanier($array){

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id IN (:array) ')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();

    }

    public function byCategorie($categorie){

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.categorie = :categorie')
            ->orderBy('u.id')
            ->setParameter('categorie', $categorie);
        return $qb->getQuery()->getResult();
    }

    public function findOther($id){

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id != :id')
            ->orderBy('u.id')
            ->setMaxResults('6')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();

    }

}
