adminCategorie_index:
    path:     /
    defaults: { _controller: "AdminBundle:adminCategorie:index" }
    methods:  GET

adminCategorie_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:adminCategorie:show" }
    methods:  GET

adminCategorie_new:
    path:     /new
    defaults: { _controller: "AdminBundle:adminCategorie:new" }
    methods:  [GET, POST]

adminCategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:adminCategorie:edit" }
    methods:  [GET, POST]

adminCategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:adminCategorie:delete" }
    methods:  DELETE
